sudo: false
language: node_js
node_js:
  - "8.9.3"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add node-gyp
cache:
  yarn: true
script:
  - yarn test
  - yarn build
branches:
  except: 
    - gh-pages
deploy:
  - provider: script
    script: bash .travis_publish
    on:
      tags: true
  - provider: npm
    email: "reto@factsmission.com"
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true